/*   Messages related to the DISPL (display list) library.
/*
msg err1
  lan english -def
    Invalid indentation in DISPL file "%p1s" on line %p2i.
msg err2
  lan english -def
    Multiple LISTS commands.
    Error on line %p1i of file "P12s".
msg err3
  lan english -def
    Multiple COLORS commands.
    Error on line %p1i of file "P12s".
msg err4
  lan english -def
    Multiple VPARMS commands.
    Error on line %p1i of file "P12s".
msg err5
  lan english -def
    Multiple TPARMS commands.
    Error on line %p1i of file "P12s".
msg err6
  lan english -def
    Unrecognized command "%p1s" encountered on line %p2i of file "%p3s".
msg err7
  lan english -def
    Bad value on line %p1i of file "%p2s".
msg err8
  lan english -def
    Syntax error on line %p1i of file "%p2s".
msg err9
  lan english -def
    Invalid color ID of %p1i on line %p2i of file "%p3s".
msg err10
  lan english -def
    Duplicate definition of color %p1i, on line %p2i of file "%p3s".
msg err11
  lan english -def
    Invalid vector parameters ID of %p1i on line %p2i of file "%p3s".
msg err12
  lan english -def
    Duplicate definition of vector parameters %p1i, on line %p2i of file
    "%p3s".
msg err13
  lan english -def
    Missing parameter on line %p1i of file "%p2s".
msg err14
  lan english -def
    Extra token "%p1s" found on line %p2i of file "%p3s".
msg err15
  lan english -def
    Invalid text parameters ID of %p1i on line %p2i of file "%p3s".
msg err16
  lan english -def
    Duplicate definition of text parameters %p1i, on line %p2i of file
    "%p3s".
